classes:
- system.docker.server.single
- service.kubernetes.master.single
- system.kubernetes.control.single
parameters:
  _param:
    openstack_version: {{ cookiecutter.openstack_version }}
    openstack_replicas: 1
  kubernetes:
    master:
      version: v1.2.4
      network:
        engine: calico
        version: v0.19.0
        hash: fb5e30ebe6154911a66ec3fb5f1195b2
        private_ip_range: {{ cookiecutter.service_ip_range }}
      storage:
        engine: glusterfs
        port: 24007
        members:
        - host: {{ cookiecutter.cmp01_ip }}
          port: 24007
        - host: {{ cookiecutter.cmp02_ip }}
          port: 24007
        - host: {{ cookiecutter.cmp03_ip }}
          port: 24007
    common:
      binaries_version: v1.2.4
  salt:
    minion:
      cert:
        kube_apiserver:
          host: {{ cookiecutter.cfg01_name }}.{{ cookiecutter.domain_name }}
          authority: kubernetes
          common_name: kubernetes-server
          signing_policy: cert_server
          alternative_names: IP:{{ cookiecutter.ctl01_ip }},IP:10.254.0.1
  docker:
    host:
      container:
        calico-node:
          image: "calico/node:v0.19.0"
          runoptions:
            - -d
            - --restart=always
            - --privileged
            - -e "ETCD_AUTHORITY=${_param:single_address}:6666"
            - -e "CALICO_NETWORKING=true"
            - -e "ETCD_SCHEME=http"
            - -e "FELIX_ETCDADDR=${_param:single_address}:6666"
            - -e "FELIX_ETCDSCHEME=http"
            - -e "IP=${_param:single_address}"
            - -e "IPV6="
            - -e "AS="
            - -e "NO_DEFAULT_POOLS="
            - --net=host
            - --name=calico-node
            - -e "HOSTNAME=${linux:system:name}"
            - -v /lib/modules:/lib/modules
            - -v /var/run/calico:/var/run/calico
          cmd: /sbin/start_runit